export interface ThemeConfig {
  id: string;
  name: string;
  category: 'traditional' | 'luxury' | 'modern' | 'religious';
  description: string;
  fontHeading: string;
  fontBody: string;
  colors: {
    primary: string;
    secondary: string;
    accent: string;
  };
  classes: {
    bodyBg: string;
    cardBg: string;
    text: string;
    heading: string;
    accentText: string;
    accentBg: string;
    button: string;
    input: string;
    border: string;
    divider: string;
  };
  ornaments: {
    type: 'batik' | 'gold-vintage' | 'floral-pastel' | 'leaf-rustic' | 'arabic' | 'minimalist' | 'traditional-culture';
    topCornerClass?: string;
    bottomCornerClass?: string;
  };
  defaultEffect: 'sakura' | 'rose' | 'confetti' | 'sparkle' | 'snow' | 'bubble' | 'fireflies' | 'lantern' | 'none';
}

export const themesRegistry: Record<string, ThemeConfig> = {
  // 🏛 TRADITIONAL INDONESIA
  'jawa': {
    id: 'jawa',
    name: 'Traditional Jawa',
    category: 'traditional',
    description: 'Tema sakral adat Jawa dengan balutan warna cokelat sogan, motif batik klasik, dan aksen emas antik.',
    fontHeading: 'font-traditional-style',
    fontBody: 'font-serif',
    colors: { primary: '#8C6239', secondary: '#FDFBF7', accent: '#D4AF37' },
    classes: {
      bodyBg: 'bg-[#F9F6F0] bg-[radial-gradient(#e0d7c7_1px,transparent_1px)] [background-size:24px_24px]',
      cardBg: 'bg-white/95 border-2 border-[#8C6239]/30 rounded-2xl shadow-xl backdrop-blur-xs',
      text: 'text-[#4A3B32]',
      heading: 'text-[#7A4B28] font-semibold',
      accentText: 'text-[#D4AF37]',
      accentBg: 'bg-[#7A4B28]',
      button: 'bg-[#7A4B28] hover:bg-[#5C381E] text-[#FDFBF7] font-semibold tracking-wider rounded-xl transition-all shadow-md active:scale-95 border border-[#8C6239]',
      input: 'bg-white border border-[#8C6239]/40 text-[#4A3B32] focus:ring-2 focus:ring-[#7A4B28] focus:border-transparent rounded-lg',
      border: 'border-[#8C6239]/20',
      divider: 'w-24 h-1 bg-gradient-to-r from-transparent via-[#8C6239] to-transparent',
    },
    ornaments: { type: 'traditional-culture' },
    defaultEffect: 'lantern',
  },
  'bali': {
    id: 'bali',
    name: 'Traditional Bali',
    category: 'traditional',
    description: 'Keagungan budaya Bali dengan palet warna merah koral, kuning poleng, serta hiasan emas prada.',
    fontHeading: 'font-traditional-style',
    fontBody: 'font-serif',
    colors: { primary: '#C1272D', secondary: '#FCFAF2', accent: '#FBB03B' },
    classes: {
      bodyBg: 'bg-[#FCF9F2] bg-[radial-gradient(#ebdcb4_1.5px,transparent_1.5px)] [background-size:32px_32px]',
      cardBg: 'bg-white/90 border border-[#FBB03B]/50 rounded-3xl shadow-lg backdrop-blur-xs',
      text: 'text-[#4D3A1E]',
      heading: 'text-[#C1272D] font-bold',
      accentText: 'text-[#FBB03B]',
      accentBg: 'bg-[#C1272D]',
      button: 'bg-[#C1272D] hover:bg-[#9B1C22] text-[#FCFAF2] font-bold tracking-widest rounded-full transition-all shadow-lg active:scale-95',
      input: 'bg-white border border-[#FBB03B]/60 text-[#4D3A1E] focus:ring-1 focus:ring-[#C1272D] rounded-xl',
      border: 'border-[#FBB03B]/30',
      divider: 'w-32 h-0.5 bg-[#FBB03B]',
    },
    ornaments: { type: 'traditional-culture' },
    defaultEffect: 'fireflies',
  },
  'sunda': {
    id: 'sunda',
    name: 'Traditional Sunda',
    category: 'traditional',
    description: 'Kesucian adat Sunda bernuansa hijau botani muda dengan untaian ronce melati suci.',
    fontHeading: 'font-classic-script',
    fontBody: 'font-serif',
    colors: { primary: '#1B4D3E', secondary: '#F7FCF9', accent: '#8FBC8F' },
    classes: {
      bodyBg: 'bg-[#F4FAF6] bg-[radial-gradient(#d3ebd9_1.5px,transparent_1.5px)] [background-size:28px_28px]',
      cardBg: 'bg-white/95 border border-[#1B4D3E]/20 rounded-2xl shadow-md',
      text: 'text-[#1E3A2F]',
      heading: 'text-[#1B4D3E] font-bold',
      accentText: 'text-[#2E8B57]',
      accentBg: 'bg-[#1B4D3E]',
      button: 'bg-[#1B4D3E] hover:bg-[#123329] text-white rounded-lg transition-transform active:scale-95 shadow-md font-semibold tracking-wide',
      input: 'bg-[#F7FCF9] border border-[#1B4D3E]/30 text-[#1E3A2F] focus:ring-2 focus:ring-[#8FBC8F] rounded-md',
      border: 'border-[#1B4D3E]/10',
      divider: 'w-24 h-1 bg-[#1B4D3E]/25 rounded',
    },
    ornaments: { type: 'traditional-culture' },
    defaultEffect: 'rose',
  },
  'batak': {
    id: 'batak',
    name: 'Traditional Batak',
    category: 'traditional',
    description: 'Ketegasan budaya Batak dengan warna khas merah, hitam, putih, dan ornamen ukiran Gorga.',
    fontHeading: 'font-traditional-style',
    fontBody: 'font-sans',
    colors: { primary: '#000000', secondary: '#F8F9FA', accent: '#BE1E2D' },
    classes: {
      bodyBg: 'bg-[#FAF8F5] bg-[radial-gradient(#e0c8c0_1px,transparent_1px)] [background-size:20px_20px]',
      cardBg: 'bg-white border-t-4 border-t-[#BE1E2D] border-x border-b border-gray-200 rounded-xl shadow-lg',
      text: 'text-gray-800',
      heading: 'text-[#BE1E2D] font-black',
      accentText: 'text-[#BE1E2D]',
      accentBg: 'bg-black',
      button: 'bg-black hover:bg-gray-900 text-white font-bold rounded-none border-b-4 border-b-[#BE1E2D] tracking-widest transition-colors',
      input: 'bg-white border-2 border-gray-300 focus:border-[#BE1E2D] focus:outline-none rounded-none text-sm',
      border: 'border-gray-200',
      divider: 'w-20 h-1 bg-black',
    },
    ornaments: { type: 'traditional-culture' },
    defaultEffect: 'confetti',
  },
  'minang': {
    id: 'minang',
    name: 'Traditional Minangkabau',
    category: 'traditional',
    description: 'Kemegahan ranah Minang bernuansa merah tua dipadukan dengan tenun songket emas pusaka.',
    fontHeading: 'font-traditional-style',
    fontBody: 'font-serif',
    colors: { primary: '#A61C2C', secondary: '#FDF7F5', accent: '#D4AF37' },
    classes: {
      bodyBg: 'bg-[#FAF2EE] bg-[radial-gradient(#eed0c5_1.5px,transparent_1.5px)] [background-size:28px_28px]',
      cardBg: 'bg-white border border-[#D4AF37]/45 rounded-2xl shadow-xl',
      text: 'text-[#4A1E1E]',
      heading: 'text-[#A61C2C] font-bold',
      accentText: 'text-[#D4AF37]',
      accentBg: 'bg-[#A61C2C]',
      button: 'bg-[#A61C2C] hover:bg-[#801420] text-white rounded-full tracking-wider shadow-md hover:shadow-[#D4AF37]/25 font-bold transition-all border border-[#D4AF37]',
      input: 'bg-white border border-[#D4AF37]/50 text-[#4A1E1E] focus:ring-1 focus:ring-[#A61C2C] rounded-lg',
      border: 'border-[#D4AF37]/20',
      divider: 'w-28 h-0.5 bg-gradient-to-r from-transparent via-[#D4AF37] to-transparent',
    },
    ornaments: { type: 'traditional-culture' },
    defaultEffect: 'sparkle',
  },
  'palembang': {
    id: 'palembang',
    name: 'Traditional Palembang',
    category: 'traditional',
    description: 'Kemewahan Kesultanan Palembang dengan warna merah crimson, songket sutera, dan emas mulia.',
    fontHeading: 'font-traditional-style',
    fontBody: 'font-serif',
    colors: { primary: '#800000', secondary: '#FCF9F2', accent: '#FFD700' },
    classes: {
      bodyBg: 'bg-[#FCF7ED] bg-[radial-gradient(#ebd0a8_1px,transparent_1px)] [background-size:24px_24px]',
      cardBg: 'bg-white/95 border-2 border-[#FFD700]/40 rounded-3xl shadow-lg',
      text: 'text-[#3D1D1D]',
      heading: 'text-[#800000] font-semibold',
      accentText: 'text-[#FFD700]',
      accentBg: 'bg-[#800000]',
      button: 'bg-[#800000] hover:bg-[#5C0000] text-white rounded-xl shadow-lg border border-[#FFD700]/30 font-bold',
      input: 'bg-white border border-[#FFD700]/30 focus:border-[#800000] focus:ring-1 focus:ring-[#800000] rounded-lg',
      border: 'border-[#FFD700]/10',
      divider: 'w-24 h-0.5 bg-[#FFD700]',
    },
    ornaments: { type: 'traditional-culture' },
    defaultEffect: 'lantern',
  },
  'betawi': {
    id: 'betawi',
    name: 'Traditional Betawi',
    category: 'traditional',
    description: 'Keceriaan adat Betawi berhias warna jingga, hijau terang khas kelapa, serta motif pucuk rebung.',
    fontHeading: 'font-classic-script',
    fontBody: 'font-sans',
    colors: { primary: '#FF5E00', secondary: '#F3FCF5', accent: '#00A859' },
    classes: {
      bodyBg: 'bg-[#FCFBF8] bg-[radial-gradient(#e0ebd5_1.5px,transparent_1.5px)] [background-size:30px_30px]',
      cardBg: 'bg-white border border-[#FF5E00]/20 rounded-2xl shadow-md',
      text: 'text-gray-800',
      heading: 'text-[#FF5E00] font-extrabold',
      accentText: 'text-[#00A859]',
      accentBg: 'bg-[#FF5E00]',
      button: 'bg-[#00A859] hover:bg-[#008A48] text-white rounded-full font-bold tracking-wide transition-all shadow-md',
      input: 'bg-white border border-gray-300 focus:border-[#FF5E00] focus:ring-1 focus:ring-[#FF5E00] rounded-xl',
      border: 'border-gray-100',
      divider: 'w-16 h-1 bg-[#00A859] rounded-full',
    },
    ornaments: { type: 'traditional-culture' },
    defaultEffect: 'confetti',
  },
  'bugis': {
    id: 'bugis',
    name: 'Traditional Bugis',
    category: 'traditional',
    description: 'Keanggunan budaya Bugis Makassar berselimut warna magenta sutera lipa sabbe dan aksen emas bura.',
    fontHeading: 'font-traditional-style',
    fontBody: 'font-serif',
    colors: { primary: '#B0005D', secondary: '#FDF7FA', accent: '#E0A96D' },
    classes: {
      bodyBg: 'bg-[#FDF9FB] bg-[radial-gradient(#ecd5e1_1px,transparent_1px)] [background-size:24px_24px]',
      cardBg: 'bg-white/95 border border-[#E0A96D]/40 rounded-2xl shadow-lg',
      text: 'text-[#4A1E35]',
      heading: 'text-[#B0005D] font-bold',
      accentText: 'text-[#E0A96D]',
      accentBg: 'bg-[#B0005D]',
      button: 'bg-[#B0005D] hover:bg-[#800043] text-white font-bold rounded-lg transition-transform active:scale-95 shadow-md border border-[#E0A96D]/30',
      input: 'bg-white border border-[#E0A96D]/50 focus:ring-1 focus:ring-[#B0005D] rounded-lg',
      border: 'border-[#E0A96D]/20',
      divider: 'w-24 h-1 bg-gradient-to-r from-transparent via-[#B0005D] to-transparent',
    },
    ornaments: { type: 'traditional-culture' },
    defaultEffect: 'fireflies',
  },
  'dayak': {
    id: 'dayak',
    name: 'Traditional Dayak',
    category: 'traditional',
    description: 'Kekayaan khazanah Dayak Kalimantan bercirikan ornamen khas tameng suku, warna merah tua, kuning kayu, hitam.',
    fontHeading: 'font-traditional-style',
    fontBody: 'font-sans',
    colors: { primary: '#FFC72C', secondary: '#F4F4F4', accent: '#DA291C' },
    classes: {
      bodyBg: 'bg-[#F7F5F0] bg-[radial-gradient(#dcd5c2_1.5px,transparent_1.5px)] [background-size:28px_28px]',
      cardBg: 'bg-white border border-gray-300 rounded-3xl shadow-lg',
      text: 'text-gray-900',
      heading: 'text-[#DA291C] font-black',
      accentText: 'text-[#FFC72C]',
      accentBg: 'bg-black',
      button: 'bg-black hover:bg-gray-800 text-white rounded-none font-bold tracking-widest transition-transform',
      input: 'bg-white border-2 border-gray-200 focus:border-[#DA291C] rounded-none',
      border: 'border-gray-200',
      divider: 'w-24 h-1 bg-[#DA291C]',
    },
    ornaments: { type: 'traditional-culture' },
    defaultEffect: 'fireflies',
  },
  'papua': {
    id: 'papua',
    name: 'Traditional Papua',
    category: 'traditional',
    description: 'Keindahan alam dan adat tanah Papua bernuansa cokelat kayu alami berpadu dengan lukisan kerang tifa.',
    fontHeading: 'font-traditional-style',
    fontBody: 'font-sans',
    colors: { primary: '#603813', secondary: '#FAF8F5', accent: '#D7A15C' },
    classes: {
      bodyBg: 'bg-[#F9F7F5] bg-[radial-gradient(#dfd5c8_1px,transparent_1px)] [background-size:20px_20px]',
      cardBg: 'bg-white border border-[#603813]/20 rounded-xl shadow-md',
      text: 'text-[#3E2712]',
      heading: 'text-[#603813] font-bold',
      accentText: 'text-[#D7A15C]',
      accentBg: 'bg-[#603813]',
      button: 'bg-[#603813] hover:bg-[#482A0E] text-white font-semibold rounded-lg tracking-wider transition-all shadow-md',
      input: 'bg-white border border-[#603813]/30 focus:ring-1 focus:ring-[#D7A15C] rounded-lg',
      border: 'border-[#603813]/10',
      divider: 'w-16 h-1 bg-[#603813] rounded-full',
    },
    ornaments: { type: 'traditional-culture' },
    defaultEffect: 'lantern',
  },

  // ✨ LUXURY
  'elegant-gold': {
    id: 'elegant-gold',
    name: 'Elegant Gold',
    category: 'luxury',
    description: 'Kemewahan tak lekang oleh waktu dengan perpaduan latar belakang champagne cream dan aksen emas foil berkilau.',
    fontHeading: 'font-luxury-serif',
    fontBody: 'font-sans',
    colors: { primary: '#C5A059', secondary: '#FDFBF7', accent: '#AA7C11' },
    classes: {
      bodyBg: 'bg-[#FDFBF7] bg-[radial-gradient(#e7ddc5_1px,transparent_1px)] [background-size:20px_20px]',
      cardBg: 'bg-white border border-[#C5A059]/30 rounded-2xl shadow-md',
      text: 'text-gray-700',
      heading: 'text-[#AA7C11] font-bold',
      accentText: 'text-[#C5A059] font-medium',
      accentBg: 'bg-gradient-to-r from-[#AA7C11] to-[#C5A059]',
      button: 'bg-gradient-to-r from-[#AA7C11] to-[#C5A059] hover:opacity-95 text-white font-bold tracking-widest rounded-full transition-transform active:scale-95 shadow-md',
      input: 'bg-white/80 border border-[#C5A059]/40 text-gray-700 focus:ring-1 focus:ring-[#AA7C11] rounded-lg',
      border: 'border-[#C5A059]/15',
      divider: 'w-24 h-0.5 bg-[#C5A059]',
    },
    ornaments: { type: 'gold-vintage' },
    defaultEffect: 'sparkle',
  },
  'rose-gold': {
    id: 'rose-gold',
    name: 'Rose Gold Luxury',
    category: 'luxury',
    description: 'Nuansa romantis bernuansa merah muda tembaga satin berpadu dengan aksen kemewahan nan anggun.',
    fontHeading: 'font-luxury-serif',
    fontBody: 'font-sans',
    colors: { primary: '#B76E79', secondary: '#FFFBFB', accent: '#C8838B' },
    classes: {
      bodyBg: 'bg-[#FFF9FA] bg-[radial-gradient(#ecd5d8_1px,transparent_1px)] [background-size:20px_20px]',
      cardBg: 'bg-white/95 border border-[#B76E79]/20 rounded-3xl shadow-lg',
      text: 'text-gray-700',
      heading: 'text-[#B76E79] font-bold',
      accentText: 'text-[#C8838B]',
      accentBg: 'bg-[#B76E79]',
      button: 'bg-[#B76E79] hover:bg-[#A35965] text-white rounded-full font-bold transition-all shadow-md active:scale-95',
      input: 'bg-white border border-[#B76E79]/30 text-gray-700 focus:ring-2 focus:ring-[#C8838B] focus:border-transparent rounded-xl',
      border: 'border-[#B76E79]/10',
      divider: 'w-28 h-0.5 bg-[#B76E79]/40',
    },
    ornaments: { type: 'gold-vintage' },
    defaultEffect: 'rose',
  },
  'emerald': {
    id: 'emerald',
    name: 'Emerald Green',
    category: 'luxury',
    description: 'Kedalaman warna hijau zamrud (emerald) megah berlapis bingkai ornamen benang emas bangsawan.',
    fontHeading: 'font-luxury-serif',
    fontBody: 'font-serif',
    colors: { primary: '#097969', secondary: '#F4FAF8', accent: '#D4AF37' },
    classes: {
      bodyBg: 'bg-[#F4FAF8] bg-[radial-gradient(#d3ece4_1px,transparent_1px)] [background-size:24px_24px]',
      cardBg: 'bg-white border-2 border-[#097969]/20 rounded-2xl shadow-xl',
      text: 'text-gray-800',
      heading: 'text-[#097969] font-bold',
      accentText: 'text-[#D4AF37]',
      accentBg: 'bg-[#097969]',
      button: 'bg-[#097969] hover:bg-[#075F52] text-white font-bold tracking-wider rounded-lg border border-[#D4AF37]/50 shadow-md',
      input: 'bg-white border border-[#097969]/30 focus:border-[#D4AF37] focus:ring-1 focus:ring-[#D4AF37] rounded-md',
      border: 'border-[#097969]/10',
      divider: 'w-24 h-1 bg-[#D4AF37]',
    },
    ornaments: { type: 'gold-vintage' },
    defaultEffect: 'sparkle',
  },
  'royal-navy': {
    id: 'royal-navy',
    name: 'Royal Navy',
    category: 'luxury',
    description: 'Kesyahduan biru dongker samudera royal dipadukan ornamen kembang mewah serbuk emas.',
    fontHeading: 'font-luxury-serif',
    fontBody: 'font-sans',
    colors: { primary: '#0A192F', secondary: '#F5F7FA', accent: '#C5A059' },
    classes: {
      bodyBg: 'bg-[#F5F8FC] bg-[radial-gradient(#d1e1f5_1px,transparent_1px)] [background-size:28px_28px]',
      cardBg: 'bg-white border-t-4 border-t-[#0A192F] border-x border-b border-gray-200 rounded-xl shadow-lg',
      text: 'text-[#1F2937]',
      heading: 'text-[#0A192F] font-bold',
      accentText: 'text-[#C5A059]',
      accentBg: 'bg-[#0A192F]',
      button: 'bg-[#0A192F] hover:bg-[#172A45] text-[#F5F7FA] font-bold rounded-lg tracking-wide shadow-md transition-colors',
      input: 'bg-white border border-gray-300 focus:border-[#C5A059] focus:ring-1 focus:ring-[#C5A059] rounded-lg',
      border: 'border-gray-200',
      divider: 'w-20 h-1 bg-[#C5A059]',
    },
    ornaments: { type: 'gold-vintage' },
    defaultEffect: 'sparkle',
  },
  'black-luxury': {
    id: 'black-luxury',
    name: 'Black Luxury',
    category: 'luxury',
    description: 'Nuansa misterius elegan menggunakan paduan hitam legam matte bersepuh aksen emas tembaga yang bersinar.',
    fontHeading: 'font-luxury-serif',
    fontBody: 'font-sans',
    colors: { primary: '#111111', secondary: '#1A1A1A', accent: '#D4AF37' },
    classes: {
      bodyBg: 'bg-[#111111] text-gray-200 bg-[radial-gradient(#333_1px,transparent_1px)] [background-size:24px_24px]',
      cardBg: 'bg-[#1A1A1A] border border-[#D4AF37]/35 rounded-3xl shadow-2xl shadow-[#D4AF37]/5',
      text: 'text-gray-300',
      heading: 'text-[#D4AF37] font-bold bg-gradient-to-r from-[#D4AF37] via-[#FFF3B0] to-[#C5A059] bg-clip-text text-transparent',
      accentText: 'text-[#D4AF37]',
      accentBg: 'bg-gradient-to-r from-[#D4AF37] to-[#C5A059]',
      button: 'bg-gradient-to-r from-[#D4AF37] to-[#C5A059] text-black hover:opacity-90 font-black tracking-widest rounded-full transition-transform shadow-lg active:scale-95',
      input: 'bg-[#252525] border border-[#D4AF37]/40 text-white focus:ring-2 focus:ring-[#D4AF37] rounded-xl',
      border: 'border-gray-800',
      divider: 'w-32 h-0.5 bg-gradient-to-r from-transparent via-[#D4AF37] to-transparent',
    },
    ornaments: { type: 'gold-vintage' },
    defaultEffect: 'sparkle',
  },
  'champagne': {
    id: 'champagne',
    name: 'Champagne Sparkle',
    category: 'luxury',
    description: 'Sentuhan warna pasir pantai champagne lembut bernilai prestisius tinggi yang memikat mata.',
    fontHeading: 'font-luxury-serif',
    fontBody: 'font-sans',
    colors: { primary: '#F7E7CE', secondary: '#FCFAF5', accent: '#C8A2C8' },
    classes: {
      bodyBg: 'bg-[#FAF8F5] bg-[radial-gradient(#ebdcb4_1px,transparent_1px)] [background-size:20px_20px]',
      cardBg: 'bg-white border border-[#FAF8F5]/60 shadow-md rounded-2xl',
      text: 'text-gray-700',
      heading: 'text-[#8E6E50] font-semibold',
      accentText: 'text-[#BCA374]',
      accentBg: 'bg-[#BCA374]',
      button: 'bg-[#BCA374] hover:bg-[#A68F5B] text-white rounded-full font-semibold transition-all shadow-md',
      input: 'bg-white border border-[#BCA374]/30 focus:ring-1 focus:ring-[#BCA374] rounded-lg',
      border: 'border-gray-100',
      divider: 'w-24 h-0.5 bg-[#BCA374]',
    },
    ornaments: { type: 'gold-vintage' },
    defaultEffect: 'sparkle',
  },
  'ivory-gold': {
    id: 'ivory-gold',
    name: 'Ivory Gold',
    category: 'luxury',
    description: 'Kesucian warna gading (ivory) murni bersanding dengan kemewahan sulaman emas berkilau.',
    fontHeading: 'font-luxury-serif',
    fontBody: 'font-serif',
    colors: { primary: '#FFFFF0', secondary: '#FFFFF0', accent: '#D4AF37' },
    classes: {
      bodyBg: 'bg-[#FFFFF0] bg-[radial-gradient(#ebdcb4_1px,transparent_1px)] [background-size:20px_20px]',
      cardBg: 'bg-white border border-[#D4AF37]/30 rounded-2xl shadow-sm',
      text: 'text-[#4A4A3A]',
      heading: 'text-[#AA7C11] font-bold',
      accentText: 'text-[#D4AF37]',
      accentBg: 'bg-white border border-[#D4AF37]',
      button: 'bg-[#AA7C11] hover:bg-[#885B27] text-white rounded-full font-bold shadow-md tracking-wider',
      input: 'bg-white border border-[#D4AF37]/35 focus:ring-1 focus:ring-[#AA7C11] rounded-lg',
      border: 'border-gray-200/50',
      divider: 'w-24 h-1 bg-[#D4AF37]/60 rounded-full',
    },
    ornaments: { type: 'gold-vintage' },
    defaultEffect: 'sparkle',
  },
  'royal-purple': {
    id: 'royal-purple',
    name: 'Royal Purple',
    category: 'luxury',
    description: 'Kemahkotaan warna ungu bangsawan anggun berhias detail emas berkilau layaknya istana raja.',
    fontHeading: 'font-luxury-serif',
    fontBody: 'font-sans',
    colors: { primary: '#4B0082', secondary: '#FBF9FC', accent: '#D4AF37' },
    classes: {
      bodyBg: 'bg-[#FAF6FC] bg-[radial-gradient(#ebd2fc_1px,transparent_1px)] [background-size:24px_24px]',
      cardBg: 'bg-white border border-[#4B0082]/20 rounded-2xl shadow-xl',
      text: 'text-gray-800',
      heading: 'text-[#4B0082] font-extrabold',
      accentText: 'text-[#D4AF37]',
      accentBg: 'bg-[#4B0082]',
      button: 'bg-[#4B0082] hover:bg-[#34005C] text-white font-bold rounded-xl shadow-md border border-[#D4AF37]/30',
      input: 'bg-white border border-[#4B0082]/30 focus:border-[#D4AF37] focus:ring-1 focus:ring-[#D4AF37] rounded-lg',
      border: 'border-gray-100',
      divider: 'w-24 h-1 bg-[#D4AF37]',
    },
    ornaments: { type: 'gold-vintage' },
    defaultEffect: 'sparkle',
  },

  // 🌿 MODERN
  'minimalist': {
    id: 'minimalist',
    name: 'Minimalist Charcoal',
    category: 'modern',
    description: 'Kesederhanaan modern berselaras dengan garis bersih abu arang charcoal dan desain elegan futuristik.',
    fontHeading: 'font-modern-sans',
    fontBody: 'font-sans',
    colors: { primary: '#1E293B', secondary: '#F8FAFC', accent: '#475569' },
    classes: {
      bodyBg: 'bg-[#F8FAFC] bg-[linear-gradient(to_right,#f1f5f9_1px,transparent_1px),linear-gradient(to_bottom,#f1f5f9_1px,transparent_1px)] [background-size:40px_40px]',
      cardBg: 'bg-white border border-slate-200 rounded-none shadow-xs',
      text: 'text-slate-600',
      heading: 'text-slate-900 font-extrabold tracking-tight',
      accentText: 'text-slate-800 font-semibold',
      accentBg: 'bg-slate-900',
      button: 'bg-slate-900 hover:bg-slate-800 text-white rounded-none font-bold tracking-widest transition-transform uppercase text-xs',
      input: 'bg-slate-50 border border-slate-300 text-slate-900 focus:ring-1 focus:ring-slate-900 rounded-none text-xs',
      border: 'border-slate-200',
      divider: 'w-16 h-0.5 bg-slate-900',
    },
    ornaments: { type: 'minimalist' },
    defaultEffect: 'none',
  },
  'scandinavian': {
    id: 'scandinavian',
    name: 'Scandinavian Warm',
    category: 'modern',
    description: 'Kombinasi warna kayu oak hangat, putih salju bersih, serta garis sketsa tanaman minimalis.',
    fontHeading: 'font-modern-sans',
    fontBody: 'font-sans',
    colors: { primary: '#8E8268', secondary: '#FAF8F5', accent: '#D3CBBF' },
    classes: {
      bodyBg: 'bg-[#FAF8F5] bg-[radial-gradient(#ebe3d5_1.5px,transparent_1.5px)] [background-size:32px_32px]',
      cardBg: 'bg-white border border-gray-200 rounded-3xl shadow-sm',
      text: 'text-gray-600',
      heading: 'text-[#5C523D] font-bold',
      accentText: 'text-[#8E8268]',
      accentBg: 'bg-[#8E8268]',
      button: 'bg-[#8E8268] hover:bg-[#726750] text-[#FAF8F5] font-medium rounded-xl transition-all shadow-xs active:scale-97',
      input: 'bg-white border border-[#D3CBBF] text-gray-800 focus:ring-1 focus:ring-[#8E8268] rounded-xl',
      border: 'border-gray-100',
      divider: 'w-20 h-0.5 bg-[#8E8268]',
    },
    ornaments: { type: 'leaf-rustic' },
    defaultEffect: 'snow',
  },
  'rustic': {
    id: 'rustic',
    name: 'Warm Rustic',
    category: 'modern',
    description: 'Romantisme hangat alam liar dengan dominasi warna tanah cokelat kayu, terakota, dan ranting pinus.',
    fontHeading: 'font-classic-script',
    fontBody: 'font-serif',
    colors: { primary: '#8A5A44', secondary: '#F7F2EE', accent: '#A06A50' },
    classes: {
      bodyBg: 'bg-[#F9F6F2] bg-[radial-gradient(#ebdcc3_1px,transparent_1px)] [background-size:20px_20px]',
      cardBg: 'bg-white/85 border border-[#8A5A44]/15 rounded-2xl shadow-md',
      text: 'text-[#5C3F35]',
      heading: 'text-[#8A5A44] font-bold',
      accentText: 'text-[#A06A50]',
      accentBg: 'bg-[#8A5A44]',
      button: 'bg-[#8A5A44] hover:bg-[#6F4432] text-white rounded-lg transition-transform active:scale-95 font-semibold shadow-xs',
      input: 'bg-[#F7F2EE] border border-[#8A5A44]/30 focus:ring-1 focus:ring-[#A06A50] rounded-md',
      border: 'border-[#8A5A44]/10',
      divider: 'w-24 h-1 bg-[#8A5A44]/40 rounded-full',
    },
    ornaments: { type: 'leaf-rustic' },
    defaultEffect: 'fireflies',
  },
  'floral': {
    id: 'floral',
    name: 'Pastel Floral',
    category: 'modern',
    description: 'Keindahan taman bunga musim semi dengan latar belakang putih suci berhias buket bunga pastel.',
    fontHeading: 'font-classic-script',
    fontBody: 'font-sans',
    colors: { primary: '#D4A5B8', secondary: '#FFF9FA', accent: '#E8C5D0' },
    classes: {
      bodyBg: 'bg-[#FFF9FB] bg-[radial-gradient(#faebf0_1.5px,transparent_1.5px)] [background-size:28px_28px]',
      cardBg: 'bg-white/95 border border-[#D4A5B8]/20 rounded-3xl shadow-sm',
      text: 'text-gray-600',
      heading: 'text-[#C785A3] font-bold',
      accentText: 'text-[#D4A5B8]',
      accentBg: 'bg-[#D4A5B8]',
      button: 'bg-[#D4A5B8] hover:bg-[#BD859E] text-white rounded-full font-semibold transition-all shadow-xs',
      input: 'bg-white border border-[#E8C5D0] focus:ring-1 focus:ring-[#D4A5B8] rounded-xl',
      border: 'border-pink-50',
      divider: 'w-20 h-0.5 bg-[#D4A5B8]/50',
    },
    ornaments: { type: 'floral-pastel' },
    defaultEffect: 'sakura',
  },
  'garden': {
    id: 'garden',
    name: 'Botanical Garden',
    category: 'modern',
    description: 'Kesegaran taman hijau alami dengan warna daun sage klorofil segar berpadu dengan mawar putih bersemi.',
    fontHeading: 'font-elegant-serif',
    fontBody: 'font-sans',
    colors: { primary: '#606C38', secondary: '#FEFAE0', accent: '#A3B18A' },
    classes: {
      bodyBg: 'bg-[#F9FCF7] bg-[radial-gradient(#e5edd7_1px,transparent_1px)] [background-size:20px_20px]',
      cardBg: 'bg-white/95 border border-[#606C38]/20 rounded-3xl shadow-sm',
      text: 'text-[#2C3E20]',
      heading: 'text-[#3E4F28] font-bold',
      accentText: 'text-[#606C38]',
      accentBg: 'bg-[#3E4F28]',
      button: 'bg-[#3E4F28] hover:bg-[#2A371A] text-white rounded-full transition-transform shadow-xs',
      input: 'bg-white border border-[#A3B18A]/60 focus:ring-1 focus:ring-[#606C38] rounded-xl',
      border: 'border-[#606C38]/10',
      divider: 'w-24 h-0.5 bg-[#606C38]/40',
    },
    ornaments: { type: 'leaf-rustic' },
    defaultEffect: 'fireflies',
  },
  'boho': {
    id: 'boho',
    name: 'Bohemian Earth',
    category: 'modern',
    description: 'Kebebasan jiwa bohemian berbalut warna terracotta hangat, ornamen pampa kering kering berkibar.',
    fontHeading: 'font-classic-script',
    fontBody: 'font-sans',
    colors: { primary: '#C86B4B', secondary: '#FCF8F5', accent: '#E39B7D' },
    classes: {
      bodyBg: 'bg-[#FDF9F6] bg-[radial-gradient(#ebd0c5_1.5px,transparent_1.5px)] [background-size:32px_32px]',
      cardBg: 'bg-white border border-[#C86B4B]/20 rounded-2xl shadow-md',
      text: 'text-[#6C4235]',
      heading: 'text-[#C86B4B] font-bold',
      accentText: 'text-[#E39B7D]',
      accentBg: 'bg-[#C86B4B]',
      button: 'bg-[#C86B4B] hover:bg-[#A14E30] text-white font-bold rounded-xl transition-all shadow-xs',
      input: 'bg-white border border-[#E39B7D] focus:ring-1 focus:ring-[#C86B4B] rounded-lg',
      border: 'border-[#C86B4B]/10',
      divider: 'w-20 h-1 bg-[#C86B4B]/30 rounded-full',
    },
    ornaments: { type: 'leaf-rustic' },
    defaultEffect: 'fireflies',
  },
  'glassmorphism': {
    id: 'glassmorphism',
    name: 'Glassmorphism Neon',
    category: 'modern',
    description: 'Visual futuristik menggunakan efek frosted glass tembus pandang bersanding dengan efek neon berpendar.',
    fontHeading: 'font-modern-sans',
    fontBody: 'font-sans',
    colors: { primary: '#6366F1', secondary: '#0F172A', accent: '#10B981' },
    classes: {
      bodyBg: 'bg-[#0B0F19] text-gray-200 bg-[linear-gradient(to_right,#111827_1px,transparent_1px),linear-gradient(to_bottom,#111827_1px,transparent_1px)] [background-size:36px_36px]',
      cardBg: 'bg-[#151D30]/65 border border-white/10 backdrop-blur-md rounded-2xl shadow-xl',
      text: 'text-gray-300',
      heading: 'text-white font-black tracking-wider bg-gradient-to-r from-cyan-400 via-indigo-400 to-emerald-400 bg-clip-text text-transparent',
      accentText: 'text-cyan-400',
      accentBg: 'bg-indigo-600',
      button: 'bg-gradient-to-r from-indigo-500 to-cyan-500 hover:from-indigo-600 hover:to-cyan-600 text-white rounded-xl font-semibold transition-transform active:scale-95 shadow-lg shadow-indigo-500/20',
      input: 'bg-[#1E293B]/80 border border-white/10 text-white focus:border-cyan-400 focus:outline-none rounded-lg',
      border: 'border-white/5',
      divider: 'w-32 h-0.5 bg-gradient-to-r from-transparent via-cyan-500 to-transparent',
    },
    ornaments: { type: 'minimalist' },
    defaultEffect: 'sparkle',
  },
  'contemporary': {
    id: 'contemporary',
    name: 'Contemporary Teal',
    category: 'modern',
    description: 'Gaya seni kontemporer dengan palet warna biru toska tua (teal) berpadu dengan abu-abu halus.',
    fontHeading: 'font-modern-sans',
    fontBody: 'font-sans',
    colors: { primary: '#008080', secondary: '#FAFDFD', accent: '#20B2AA' },
    classes: {
      bodyBg: 'bg-[#FAFCFC] bg-[radial-gradient(#def2f2_1.5px,transparent_1.5px)] [background-size:28px_28px]',
      cardBg: 'bg-white border border-teal-100 rounded-2xl shadow-xs',
      text: 'text-[#1F3D3D]',
      heading: 'text-[#006666] font-bold',
      accentText: 'text-[#20B2AA]',
      accentBg: 'bg-[#008080]',
      button: 'bg-[#008080] hover:bg-[#005757] text-white font-bold rounded-lg transition-all shadow-xs',
      input: 'bg-white border border-teal-200 focus:ring-1 focus:ring-[#008080] rounded-lg',
      border: 'border-teal-50',
      divider: 'w-24 h-0.5 bg-[#008080]/30',
    },
    ornaments: { type: 'minimalist' },
    defaultEffect: 'bubble',
  },

  // 🕌 RELIGIOUS
  'islamic': {
    id: 'islamic',
    name: 'Islamic Arabesque',
    category: 'religious',
    description: 'Kesakralan nilai islami berbalut warna hijau jamrud istimewa dengan ornamen kubah masjid arabesque emas.',
    fontHeading: 'font-arabic-style',
    fontBody: 'font-serif',
    colors: { primary: '#0B6623', secondary: '#FAFDF9', accent: '#D4AF37' },
    classes: {
      bodyBg: 'bg-[#FAFDF9] bg-[radial-gradient(#e0f2e4_1.5px,transparent_1.5px)] [background-size:24px_24px]',
      cardBg: 'bg-white border-2 border-[#D4AF37]/35 rounded-3xl shadow-lg',
      text: 'text-[#1E3E26]',
      heading: 'text-[#0B6623] font-bold',
      accentText: 'text-[#D4AF37]',
      accentBg: 'bg-[#0B6623]',
      button: 'bg-[#0B6623] hover:bg-[#084D1A] text-white font-bold rounded-xl transition-all shadow-md border border-[#D4AF37]/30',
      input: 'bg-white border border-[#D4AF37]/40 text-[#1E3E26] focus:ring-1 focus:ring-[#0B6623] rounded-lg',
      border: 'border-[#D4AF37]/15',
      divider: 'w-32 h-1 bg-[#D4AF37]/75 rounded-full',
    },
    ornaments: { type: 'arabic' },
    defaultEffect: 'lantern',
  },
  'christian': {
    id: 'christian',
    name: 'Christian Holy White',
    category: 'religious',
    description: 'Kesucian janji suci kristiani berhias marmer putih bersih serta simbol salib floral yang elegan.',
    fontHeading: 'font-elegant-serif',
    fontBody: 'font-serif',
    colors: { primary: '#605B56', secondary: '#FFFFFF', accent: '#A09890' },
    classes: {
      bodyBg: 'bg-[#FCFAF8] bg-[radial-gradient(#eee4dc_1px,transparent_1px)] [background-size:20px_20px]',
      cardBg: 'bg-white border border-gray-200 rounded-xl shadow-sm',
      text: 'text-gray-700',
      heading: 'text-[#605B56] font-bold tracking-wide',
      accentText: 'text-[#A09890]',
      accentBg: 'bg-[#605B56]',
      button: 'bg-[#605B56] hover:bg-[#484440] text-white font-semibold rounded-lg tracking-widest transition-transform active:scale-95 shadow-xs',
      input: 'bg-white border border-gray-300 focus:ring-1 focus:ring-[#605B56] rounded-md',
      border: 'border-gray-150',
      divider: 'w-20 h-0.5 bg-[#A09890]',
    },
    ornaments: { type: 'floral-pastel' },
    defaultEffect: 'snow',
  },
  'catholic': {
    id: 'catholic',
    name: 'Catholic Classical',
    category: 'religious',
    description: 'Kemegahan liturgi klasik katedral katolik bermotif jendela kaca patri berwarna dan emas antik.',
    fontHeading: 'font-elegant-serif',
    fontBody: 'font-serif',
    colors: { primary: '#4A3B32', secondary: '#FDFBF7', accent: '#C5A059' },
    classes: {
      bodyBg: 'bg-[#FCFAF6] bg-[radial-gradient(#eadaad_1px,transparent_1px)] [background-size:24px_24px]',
      cardBg: 'bg-white/95 border border-[#C5A059]/40 rounded-2xl shadow-md',
      text: 'text-[#4A3B32]',
      heading: 'text-[#4A3B32] font-semibold',
      accentText: 'text-[#C5A059]',
      accentBg: 'bg-[#4A3B32]',
      button: 'bg-[#4A3B32] hover:bg-[#342922] text-[#FDFBF7] font-semibold rounded-full shadow-md tracking-wider',
      input: 'bg-white border border-[#C5A059]/40 focus:ring-1 focus:ring-[#4A3B32] rounded-lg',
      border: 'border-[#C5A059]/10',
      divider: 'w-24 h-0.5 bg-[#C5A059]',
    },
    ornaments: { type: 'gold-vintage' },
    defaultEffect: 'lantern',
  },
  'hindu': {
    id: 'hindu',
    name: 'Hindu Mandala',
    category: 'religious',
    description: 'Kesucian upacara Hindu berselimut warna kuning jingga safron suci berhias motif mandala sakral.',
    fontHeading: 'font-traditional-style',
    fontBody: 'font-serif',
    colors: { primary: '#E65C00', secondary: '#FFFDF9', accent: '#FF9933' },
    classes: {
      bodyBg: 'bg-[#FFFDF9] bg-[radial-gradient(#ffdcb3_1.5px,transparent_1.5px)] [background-size:28px_28px]',
      cardBg: 'bg-white border border-[#FF9933]/55 rounded-3xl shadow-lg',
      text: 'text-[#4A2300]',
      heading: 'text-[#E65C00] font-bold',
      accentText: 'text-[#FF9933]',
      accentBg: 'bg-[#E65C00]',
      button: 'bg-[#E65C00] hover:bg-[#B34700] text-white font-bold rounded-xl tracking-wider transition-all shadow-md',
      input: 'bg-white border border-[#FF9933]/50 focus:ring-1 focus:ring-[#E65C00] rounded-xl',
      border: 'border-[#FF9933]/25',
      divider: 'w-28 h-0.5 bg-[#FF9933]',
    },
    ornaments: { type: 'traditional-culture' },
    defaultEffect: 'fireflies',
  },
  'buddha': {
    id: 'buddha',
    name: 'Buddha Zen Garden',
    category: 'religious',
    description: 'Kedamaian batin ajaran zen bernuansa cokelat kayu jati tua alami berlatar kembang teratai mekar.',
    fontHeading: 'font-traditional-style',
    fontBody: 'font-serif',
    colors: { primary: '#804000', secondary: '#FDFBF7', accent: '#D4AF37' },
    classes: {
      bodyBg: 'bg-[#FAF8F5] bg-[radial-gradient(#e7dcc5_1px,transparent_1px)] [background-size:20px_20px]',
      cardBg: 'bg-white border border-[#804000]/15 rounded-2xl shadow-sm',
      text: 'text-[#3E1F00]',
      heading: 'text-[#804000] font-semibold',
      accentText: 'text-[#D4AF37]',
      accentBg: 'bg-[#804000]',
      button: 'bg-[#804000] hover:bg-[#592D00] text-white rounded-lg transition-transform font-bold active:scale-95 shadow-xs',
      input: 'bg-white border border-[#804000]/25 focus:ring-1 focus:ring-[#804000] rounded-md',
      border: 'border-gray-150',
      divider: 'w-20 h-1 bg-[#D4AF37]/50 rounded-full',
    },
    ornaments: { type: 'traditional-culture' },
    defaultEffect: 'lantern',
  },
};

export function getThemeConfig(id: string): ThemeConfig {
  return themesRegistry[id] || themesRegistry['elegant-gold'];
}

export function getAllThemes(): ThemeConfig[] {
  return Object.values(themesRegistry);
}
